const Queries = [
  '10 days in the Americas',
  '10 game superset with cribbage',
  '100 mille bornes',
  '100 wacky things',
  '100 wacky things',
  '1754 conquest',
  '1775 American revolution',
  '5 second rule',
  '5-minute dungeon',
  '7 wonders',
  '878 Vikings',
  'A series of unfortunate events',
  'A series of unfortunate events',
  'Above and below',
  'Adventurers',
  'Adverteasing',
  'Alan’s Adventureland',
  'Alienz',
  'Amasser dragons',
  'Amoeba',
  'Among thieves',
  'Ancient civilizations',
  'Ancient civilizations of the inner sea',
  'Anger management',
  'Angry birds card game',
  'Angry birds on thin ice',
  'Anti-monopoly',
  'Ants in your pants',
  'Apple’s to apple’s kids',
  'Apple’s to apple’s party box',
  'Apple’s to apple’s to go',
  'Arcane legion',
  'Are you smarter than a 5th grader?',
  'Area project',
  'Arena of the gods',
  'Artifacts inc.',
  'Attack on titan',
  'Avengers war & rummy',
  'Backgammon',
  'Backgammon',
  'Bakugan brawl',
  'Balloon pop',
  'Bananagrams',
  'Bananagrams wild tiles',
  'Bang',
  'Barbarians',
  'Barkers row',
  'Barrel of monkeys',
  'Batman Arkham city escape',
  'Batman returns',
  'Batman the animated series masterminds & mayhem',
  'Batman the animated series rogue gallery',
  'Battle for greyport',
  'battle for Stalingrad',
  'Battle lines',
  'Battle of the sexes',
  'Battle of the sexes',
  'Battleship',
  'Beam me up',
  'Bears and the bees',
  'Beat the parents',
  'Bed bugs',
  'Beetle apples to apples to go',
  'Befuddled',
  'Berserk',
  'Betrayal at baulders gate',
  'Bicycle cards',
  'Bid it',
  'Big boggle',
  'Bing-oh',
  'Biotix',
  'Black box',
  'Blokus',
  'Blokus trigon',
  'Blue lagoon',
  'Bodger mania',
  'Bohnaparte',
  'Bold',
  'Book of Mormon battles',
  'Book of Mormon battles',
  'Book of Mormon big dig',
  'Boom-o',
  'Boss monsters 2',
  'Boss monsters with ALL expansions',
  'Bottle imp',
  'Bounce off',
  'Bowling dice',
  'Bowling dice',
  'Brain quest',
  'Broadsides',
  'Brown bear panda bear what do you see',
  'Buck buck moose',
  'Burger joint',
  'Burial',
  'But so fast',
  'Button men',
  'Buzz off',
  'Call to adventure',
  'Call to adventure name of the wind',
  'Canasta deluxe',
  'Candy land',
  'Caravan',
  'Carcasone',
  'Card city xl',
  'Castle of mad king Ludwig',
  'Castle of the devil',
  'Castle panic',
  'Cat and the fiddle',
  'Cat in the hat I can do that',
  'Cat stax',
  'Catacombs',
  'Catalyst',
  'Catan',
  'Catan',
  'Catan adventures candamir',
  'catan game of thrones',
  'Catan histories settlers of America',
  'Catan portable',
  'Catch phrase',
  'Catch phrase',
  'catchword',
  'Caveman quest for fire',
  'Centipede',
  'Chain game',
  'Chatter matters',
  'Checkers Broncos',
  'Chef cuckoo!',
  'Chess',
  'Chess checkers & tic tac toe',
  'Chess on the loose',
  'Chicken or egg',
  'Chris is Tokyo',
  'Chrononauts',
  'Churchill',
  'Chutes and ladders My little pony',
  'Cinelinx',
  'Cinelinx blue',
  'Cinelinx red',
  'City of iron',
  'City of spies',
  'Clash of giants civil war',
  'Clue',
  'Clue 1962',
  'Clue secrets and spies',
  'Code sudoku',
  'Colonial',
  'Comanauts',
  'Conan',
  'Conflicting legends',
  'Connect 4',
  'Conquest of speros',
  'Constantonopolous',
  'Construction',
  'Cornhole mini',
  'Coup',
  'Cover up',
  'Cowboy bebop',
  'Crabs adjust humidity',
  'Cranium hoopla',
  'Cranium wow you’re good',
  'Crank!',
  'Crazy eights',
  'Cribbage',
  'cribbage',
  'CSI civil war',
  'CSI cranium cadoo',
  'CSI Miami',
  'Cthulhu realms',
  'Curses',
  'CV pocket',
  'D&D assault of the giants',
  'D&D Castle ravenloft',
  'D&D dragonfire',
  'D&D Legend of drizzt',
  'D&D tomb of annihilation',
  'D&D tyrants of the darkness',
  'D&D wrath of ashardalon',
  'Da Vinci’s challenge',
  'Dao',
  'Dark souls',
  'Dear in the headlights',
  'Deskto beanbag toss',
  'Diary of a wimpy kid cheese touch',
  'Diary of a wimpy kid don’t scramble the egg',
  'Dice forge',
  'Dice stack',
  'Dice wars - war of light',
  'Dicecapades!',
  'Dinosaur island',
  'Dinosaur island totally liquid',
  'Disney villainous',
  'Dixit',
  'Djinns',
  'Doctor! Doctor!',
  'Dominion',
  'Domino’s',
  'Domino’s',
  'Don’t bother the mouse',
  'Don’t let the marbles fall',
  'Doodle cube',
  'Doomtown reloaded',
  'Double shutter',
  'Double take',
  'Dragon farkle',
  'Dragon scales',
  'Dragonology',
  'Drive',
  'Driving dead',
  'Duck dynasty',
  'Duck dynasty',
  'Dungeon busters',
  'Dutch blitz',
  'Easy come easy go',
  'Edition wars',
  'Eight minute empire',
  'El caballero',
  'Elephants trunk',
  'Elixir',
  'empire’s of the void 2',
  'Energy empire',
  'Euphoria',
  'Evolution',
  'Ex Liberia',
  'Exploding kittens',
  'Faces',
  'Fact or crap',
  'Family business',
  'Family challenge',
  'Family feud strike out',
  'Farkle',
  'Farkle shake and go',
  'Fate of the elder gods',
  'Feast and famine',
  'Finger guns',
  'First Martinson’s',
  'Fist full of penguins',
  'Five little monkeys jumping on the bed',
  'Fleecing Olympus',
  'Flurry!',
  'fluxx',
  'Flying goblin',
  'Fog of war',
  'Foodie fight',
  'For sale',
  'Forbidden island',
  'Force of will',
  'Force of will legacy lost',
  'Fox and geese',
  'Frenzy',
  'Frog juice',
  'Gaia project',
  'Game breaker football trivia',
  'Game of life zapped',
  'Game of phones',
  'Game of things',
  'Game of things',
  'Get the Mac-Guffin',
  'Giant spoons',
  'Global pursuit',
  'Gloom fairy tale',
  'Gloom fairytale',
  'Gloom in space',
  'Gloomhaven',
  'Gloria mundi',
  'Go',
  'Go go galato!',
  'Go nuts',
  'goatfish',
  'Godfather',
  'Golf dice game',
  'Good cop bad cop',
  'Grabolo',
  'Great cheese chase',
  'Guatemala cafe',
  'Guess who',
  'Guildhall',
  'Half wits',
  'Halo taxdex',
  'Hangman',
  'Hangman',
  'Hare & the tortoise',
  'Have you herd?',
  'Haven',
  'Headbanz',
  'Headspace',
  'Hearing things',
  'Heaven and ale',
  'Here to slay',
  'Hero brigade',
  'Hero’s',
  'Hero’s of dominaria',
  'Hero’s of metro city',
  'Hi ho! Cherry-O',
  'Hide & seek',
  'Hilarium',
  'Hisss',
  'Hisss',
  'Hit the deck',
  'Hoard',
  'Hole in one',
  'Holland ‘44',
  'Hot potato',
  'Huggermugger',
  'Hyperberia',
  'I hate zombies',
  'I love Lucy',
  'Image',
  'Imaginiff…',
  'Imperial',
  'In a pickle',
  'In a pickle',
  'Incan gold',
  'Instant Iceland',
  'Isaac',
  'Island of doctor lucky',
  'It came to pass',
  'Jishaku',
  'Joe name it',
  'Jumanji',
  'Kahootz!',
  'Kharnage',
  'Kill doctor lucky',
  'Kill doctor lucky',
  'Killer bunny',
  'King domino',
  'Kingdom builder',
  'Kings corner',
  'Kings struggle',
  'Kitten klash',
  'Klondike rush',
  'Klondike rush',
  'Knock out',
  'Konito?',
  'Krypto',
  'Kuuduk',
  'Kvack',
  'Kvack',
  'La strada',
  'Labyrinth',
  'Labyrinth',
  'Ladybug game',
  'Lagoon land of druids',
  'Land of the guardian circle of strength',
  'Last spike',
  'Last word',
  'Left center right',
  'Legend of the five rings',
  'Legendary encounters',
  'Legendary X-men',
  'Legends of the hidden temple',
  'Lego Minotaurs',
  'Lemonade stand',
  'Liars dice',
  'Life',
  'Life adventures',
  'Likewise',
  'Limbo',
  'Linkity',
  'Linkity',
  'Loco motive',
  'Logos',
  'Loka',
  'Loony bin',
  'Looterz',
  'Lord of Hellas',
  'Lord of the rings - return of the king',
  'Lost',
  'Lost cities',
  'Mad gab',
  'Madagascar escape 2 Africa',
  'Made for trade',
  'Maidens quest',
  'Mall of horror',
  'Mammoth hunters',
  'Man laws & woman rules',
  'Mancala',
  'Manga manga',
  'Martin dice',
  'Martin’s!!!',
  'Marvel civil war jumbo cards',
  'Marvel code names',
  'Massive darkness',
  'Master fox',
  'Master of Orion',
  'Mastermind kids',
  'Matching- Garanimals',
  'Meeple war',
  'Mega land',
  'Memory',
  'Memory - Spider-Man',
  'Mexican train domino',
  'Millie Bornes',
  'Minecraft',
  'Minecraft the card game',
  'Mini tower game',
  'Minute realms',
  'Missile command',
  'Missing link',
  'Mission impossible',
  'Modern family',
  'Monopoly junior',
  'Monster rejects',
  'Monsters vs heros',
  'Mousquetaires du Roy',
  'Movie buff vol 1',
  'Mr mouth',
  'MTG battle the hoard',
  'MTG defeat a god',
  'MTG face the hydra',
  'MTG planeswalkers',
  'Munchkin',
  'Munchkin gloom',
  'My first uno',
  'Mystery at hogwarts',
  'Mythic battles',
  'Nab-it!',
  'Nano fiction',
  'Naruto shippuden',
  'Near and far',
  'Nightfall',
  'Noir of indies',
  'Noir of indies',
  'Nowhere to go',
  'Nuts about mutts',
  'Nyctophobia',
  'Ocean limbo',
  'Oh-no zombies',
  'On the dot',
  'One night revolution',
  'One night vampire',
  'One word',
  'Onitama',
  'Operation Spider-Man origins',
  'Orc-lympics',
  'orcs orcs orcs',
  'Origami',
  'Origin',
  'Outback chase',
  'Outburst remix',
  'Outpost Amazon',
  'Outpost Siberia',
  'Outta control',
  'Pack & stack',
  'Paired up',
  'Pairs',
  'Pairs deluxe',
  'Pandemic',
  'Pandemic contagion',
  'Paperback',
  'Paperback unabridged',
  'Partini',
  'Party pooper',
  'Party pooper',
  'Pass the bomb',
  'Pathfinder skull & shackles',
  'Pathfinder wrath of the righteous',
  'Pay day',
  'Peace',
  'Peanut butter & jelly',
  'Peek and push',
  'Peek and push',
  'Peloponnesian war',
  'Peloponnesian war',
  'Perfection',
  'Phantom',
  'Phase 10',
  'Phase 10',
  'Phase 10',
  'Phase 10',
  'Phase 10 dice',
  'Phase 10 dice',
  'Pictionary card came',
  'Pictionary card game',
  'Pictionary man',
  'Pikoko',
  'Pillow',
  'Pillow',
  'Pillow fight',
  'Pirate fluxx',
  'Pirates of the Caribbean pirates dice',
  'Pirates of the Caribbean pirates dice',
  'Pirates quest for Davy Jones locker',
  'Pit',
  'Pixel tactics 2',
  'Pizza to go',
  'Pocket farkle',
  'Potion explosion',
  'Pounce',
  'Press here',
  'Protect your kingdom',
  'Putter pins',
  'Pyramid of the sun',
  'Quack quack',
  'Quarx',
  'Quelf',
  'Quelf antics',
  'Quelf antics',
  'Quest for Atlantis',
  'Quest of the philosophers stone',
  'Quick cups',
  'Quiddler',
  'Raceway 57',
  'Rack-o',
  'Rage',
  'Ragers',
  'Rat-a-tat cat',
  'Rats card game',
  'Ratuki',
  'Redneck life',
  'Resident evil',
  'Resistance',
  'Resistance',
  'Respond!',
  'Rhino hero',
  'Risk',
  'Risk marvel',
  'Risk transformers',
  'Rob ‘n run',
  'Robot turtles',
  'Robotech',
  'Rock the beat',
  'Rook',
  'Rorshock in color',
  'Rotten apples',
  'RPG call of Cthulhu 7th edition rules',
  'RPG call of Cthulhu alone against the dark',
  'RPG call of Cthulhu alone against the flame',
  'RPG call of Cthulhu curious characters',
  'RPG call of Cthulhu phobia deck',
  'RPG call of Cthulhu unfortunate events',
  'RPG call of Cthulhu weapons and artifacts',
  'RPG D&D masters of the wild',
  'RPG post apocalyptic blues',
  'RPG rune quest',
  'RPG Star Wars 2nd edition core rules',
  'RPG Star Wars cravens rebel operatives',
  'RPG Star Wars Death Star technical companion',
  'RPG Star Wars movie source book',
  'RPG Warhammer dark heresy church of the damned',
  'RPG Warhammer fantasy role play',
  'RPG wheel of time',
  'Rsvp',
  'Ruckus',
  'Rules of the game',
  'Rummikub',
  'Rummikub dice',
  'Rummy',
  'Sagrada',
  'Santorini',
  'Scary tales lil red vs Pinocchio',
  'Scary tales storyline',
  'Scrabble',
  'Scrabble dictionary',
  'Scrabble flash',
  'Scrabble slam',
  'Scrabble turbo slam',
  'Scrabbled states of America',
  'Scum',
  'Sea battle',
  'Search, ponder and play',
  'Seek',
  'Senat',
  'Sequence',
  'Sequence dice',
  'Serpent master',
  'Set',
  'Shadowrift',
  'Shadowrun zero day',
  'Shadowscape',
  'Shark',
  'Sheriff of Nottingham',
  'Skip-Bo',
  'Slam',
  'Slamphoria',
  'Slamwitch',
  'slapzi',
  'Smash up base',
  'Smash up monster mash',
  'Smash up science fiction double feature',
  'Smash up what were we thinking',
  'Smithsonian artifact or fiction',
  'Snakes & ladders',
  'Sneakers',
  'Sneaky snacky squirrel',
  'Snorta',
  'Snorta',
  'Song of fire and ice',
  'Sorry',
  'Sorry',
  'Sorry revenge',
  'Sorry sliders',
  'Sorry spin',
  'Sorry spin',
  'Sovereigns chain',
  'Space corps 2025-2300ad',
  'Space dash',
  'Space team',
  'Spaghetti and math balls',
  'Sparkle kitty',
  'Speak it not',
  'Speak out loud',
  'Spider-Man trick shot',
  'Spoils of war',
  'Spot it!',
  'Spot it! Halloween',
  'Star Wars angry birds millennium falcon',
  'Star Wars battle for Naboo',
  'Star Wars destiny',
  'Star Wars galactic dice',
  'Star Wars Imperial assault',
  'Star Wars imperial assault Java’s realm',
  'Star Wars Jedi unleashed',
  'Star Wars legion',
  'Star Wars monopoly',
  'Star Wars Star destroyer strike',
  'Starfighter',
  'Stixx',
  'Stone soup',
  'Storm the castle',
  'Storybook',
  'Straight 4',
  'Stratego',
  'Stratego',
  'Stupor',
  'Submarine',
  'Super Mario level up!',
  'Survive',
  'Sushi bar',
  'Sushi go',
  'Swap',
  'Sword art online',
  'Taboo',
  'Take away',
  'Tall tales it’s a weird world',
  'Talon',
  'Tangoes',
  'Tax and spend',
  'Temporum',
  'Tennis shoes among the nephites',
  'Tennis shoes among the nephites',
  'Terraforming Mars',
  'Tetris',
  'Tetris link',
  'Thataway!',
  'The yeti salon',
  'Therapy',
  'Thunder ally',
  'Tic tax toe',
  'Ticket to ride',
  'Ticket to ride London',
  'Tiddlywinks',
  'Tiffin',
  'Tile twist',
  'Timeline diversity',
  'Timeline inventions',
  'Timeline science and discoveries',
  'Tiny epic defenders',
  'Tiny epic defenders',
  'Tiny epic defenders',
  'Tiny epic defenders dark wars',
  'Tiny epic kingdoms',
  'Tiny epic mechs',
  'Tiny epic quest',
  'Tiny epic westerns',
  'Tiny towns',
  'Tip of the tongue',
  'Titan rage',
  'Topple',
  'Totally awesome!',
  'Totally gross!',
  'Tournament at Camelot',
  'Towers of arkhanos',
  'Trans America',
  'Trek to Zion',
  'Tri-bond',
  'Tri-versity',
  'Triominos',
  'Trivial pursuit sports & games',
  'True colors',
  'Tsuro of the sea',
  'Tudor',
  'Twilight imperium 3rd edition',
  'Twilight struggle',
  'Twist of fate',
  'Typo',
  'Typo',
  'Ubongo',
  'Ultimate golf',
  'Ultimate werewolf',
  'Uncle wiggly',
  'Unearth',
  'unexploded cow',
  'Uno deluxe',
  'Uno disney',
  'Uno Harry Potter',
  'Uno house rules',
  'Uno moo',
  'Uno robot',
  'Uptown',
  'Urban dictionary game',
  'Urban legends',
  'Urban myth',
  'Utopia',
  'Utopia',
  'Vampire hunter',
  'Villainous',
  'Visual eyes',
  'Voodoo',
  'Wacky white elephant',
  'Walking dead',
  'Walking dead dice game',
  'Wanna bet?',
  'Wanted rich or dead',
  'Warmachine retribution of sscyrah',
  'Warmachine skorne',
  'War time',
  'Warcraft- onyxias lair',
  'Warhammer nightvault',
  'Warhammer shadowspire',
  'Warriors from the promised land',
  'Wasteland express',
  'Waterworks',
  'We didn’t play test this at all',
  'Welcome to the dungeon',
  'Werewolf',
  'Whac-a-mole',
  'What are the odds',
  'What should you do',
  'What were you thinking?',
  'What’s up',
  'What’s yours like?',
  'Wheel of fortune',
  'Where’s bobs hat',
  'Where’s my water',
  'Which one?',
  'Whits and wagers',
  'Wise Alec',
  'Wise and otherwise',
  'Wish jr.',
  'Wishing quest',
  'Wits and wagers',
  'Wizard of oz',
  'Word search!',
  'Word setters',
  'Word setters',
  'Word slam',
  'World war z',
  'Would you rather…',
  'Xoom cubes',
  'Yahtzee',
  'Yahtzee flash',
  'Yak',
  'Yali',
  'Yellowstone travel pack',
  'Yhatzee classic',
  'You to the rescue',
  'You’ve got crabs',
  'Zero',
  'Zeus on the loose',
  'Zigity',
  'ZigZag',
  'Zingers',
  'Zip-it',
  'Zobmondo!!',
  'Zombicide green hoard',
  'Zombicide hoard box',
  'Zombie dice hoard edition',
  'Zombieopoly',
  'Zombies keep out',
  'Zombies!!!',
  'Zooloretto',
  'Query',
];

module.exports =Queries
